name: Deploy Firebase Data Connect

on:
  push:
    branches:
      - main # Или другая основная ветка вашего репозитория
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите версию Node.js, которую используете

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_TOKEN }}" | firebase login --token

      - name: Deploy Data Connect
        run: firebase deploy --only dataconnect
